/* geebr.world v8 — real Quaternius GLTF prop assets + bigger toybox; no LLM plugin yet */
const canvas = document.getElementById('renderCanvas');
const ASSET = './assets/textures/';
const PROP_ASSET = './assets/models/props/';
const WORLD = { size: 32, half: 16 };
const COMMANDS = ['say','walk','look','touch','push','pull','carry','drop','throw','dig','build','repair','panic','spell.push','spell.spark','spell.fireball'];
const state = {
  scene:null, engine:null, camera:null, shadow:null, materials:{}, geebrs:[], selected:null, target:null,
  blocks:[], props:[], bubbles:[], badges:[], meta:new Map(), held:new Map(), allowed:new Set(COMMANDS)
};
function log(s){ const box=document.getElementById('log'); const div=document.createElement('div'); div.className='logline'; div.textContent=s; box.prepend(div); while(box.children.length>10) box.lastChild.remove(); }
function pickRandom(a){ return a[Math.floor(Math.random()*a.length)] }
function clamp(v,a,b){ return Math.max(a,Math.min(b,v)); }
async function createEngine(){ if(!navigator.gpu) throw new Error('WebGPU unavailable in this browser'); const engine = new BABYLON.WebGPUEngine(canvas,{antialias:true,adaptToDeviceRatio:true}); await engine.initAsync(); return engine; }
function mat(scene,name,texture,opts={}){ const m=new BABYLON.StandardMaterial(name,scene); m.diffuseTexture=new BABYLON.Texture(ASSET+texture,scene,true,false,BABYLON.Texture.NEAREST_SAMPLINGMODE); m.diffuseTexture.uScale=opts.uScale||1; m.diffuseTexture.vScale=opts.vScale||1; m.specularColor=opts.specular||new BABYLON.Color3(.035,.035,.03); if(opts.emissive) m.emissiveColor=opts.emissive; return m; }
function colorMat(scene,name,color,emissive=null){ const m=new BABYLON.StandardMaterial(name,scene); m.diffuseColor=color; m.specularColor=new BABYLON.Color3(.035,.035,.035); if(emissive) m.emissiveColor=emissive; return m; }
function addShadow(mesh){ if(state.shadow && mesh) { try { state.shadow.addShadowCaster(mesh,true); } catch{} } }
function addBody(mesh,motion,shape='BOX',mass=1,opts={}){ if(!BABYLON.PhysicsBody) return null; const agg=new BABYLON.PhysicsAggregate(mesh,BABYLON.PhysicsShapeType[shape],{mass,friction:opts.friction??.82,restitution:opts.restitution??.08},state.scene); if(motion==='static') agg.body.setMotionType(BABYLON.PhysicsMotionType.STATIC); return agg; }
function tag(mesh,type,extra={}){ state.meta.set(mesh,{type,state:extra.state||'intact',material:extra.material||type,health:extra.health??2,interactive:extra.interactive!==false,zone:extra.zone||'world',flammable:!!extra.flammable, soft:!!extra.soft}); mesh.metadata=state.meta.get(mesh); return mesh; }
function meta(mesh){ const m=state.meta.get(mesh)||mesh?.metadata; if(m?.proxy) return state.meta.get(m.proxy)||m.proxy.metadata; return m; }
function logicalTarget(mesh){ const m=state.meta.get(mesh)||mesh?.metadata; return m?.proxy || mesh; }
function damage(mesh,amount=1,kind='hit'){
  const m=meta(mesh); if(!m || !m.interactive) return;
  m.health-=amount;
  if(kind==='fire') { m.state='burned'; if(mesh.material!==state.materials.burned) mesh.material=state.materials.burned; emitBadge(mesh,'scorch'); }
  else if(m.health<=1 && m.state==='intact') { m.state='cracked'; if(state.materials.cracked) mesh.material=state.materials.cracked; emitBadge(mesh,'crack'); }
  if(m.health<=0) breakObject(mesh,kind);
}
function breakObject(mesh,kind='hit'){
  const m=meta(mesh); if(!m || m.state==='broken') return; m.state='broken'; emitBadge(mesh,kind==='fire'?'poof':'bonk');
  const p=mesh.getAbsolutePosition().clone(); const material=mesh.material; const count=m.type==='wall'?7:5;
  if(mesh.physicsBody){ try{ mesh.physicsBody.dispose(); }catch{} }
  mesh.dispose(); state.props=state.props.filter(x=>x!==mesh); state.blocks=state.blocks.filter(x=>x!==mesh); state.meta.delete(mesh);
  for(let i=0;i<count;i++){ const s=BABYLON.MeshBuilder.CreateBox('rubble_'+m.type,{size:.18+Math.random()*.22},state.scene); s.position=p.add(new BABYLON.Vector3((Math.random()-.5)*.55,.2+Math.random()*.4,(Math.random()-.5)*.55)); s.rotation.set(Math.random(),Math.random(),Math.random()); s.material=material||state.materials.stone; addBody(s,'dynamic','BOX',.18,{restitution:.18}); addShadow(s); tag(s,'rubble',{health:1,interactive:false}); const v=new BABYLON.Vector3(Math.random()-.5,.6,Math.random()-.5).scale(1.8); s.physicsBody?.applyImpulse(v,s.position); setTimeout(()=>s.dispose(),8500); }
}
function impulse(mesh,from,power,up=.25){ if(!mesh?.physicsBody) return; const dir=mesh.getAbsolutePosition().subtract(from); if(dir.length()<.001) dir.set(Math.random()-.5,0,Math.random()-.5); dir.y=up; dir.normalize(); mesh.physicsBody.applyImpulse(dir.scale(power),mesh.getAbsolutePosition()); }
function emitBadge(target,text){ const div=document.createElement('div'); div.className='badge'; div.textContent=text; document.body.appendChild(div); const node=target.root||target; state.badges.push({div,node,ttl:1.05,vy:-28}); }
function lowPolyBlob(name,scene,rx=.5,ry=.6,rz=.4,rings=5,seg=8){ const positions=[],indices=[],normals=[],uvs=[]; for(let r=0;r<=rings;r++){ const v=r/rings,phi=-Math.PI/2+v*Math.PI,y=Math.sin(phi)*ry,cr=Math.cos(phi); const wob=1+(r%2?.06:-.025); for(let s=0;s<seg;s++){ const u=s/seg,th=u*Math.PI*2; positions.push(Math.cos(th)*rx*cr*wob*(1+.04*Math.sin(3*th)),y,Math.sin(th)*rz*cr*wob*(1+.04*Math.cos(2*th))); uvs.push(u,v); } } for(let r=0;r<rings;r++) for(let s=0;s<seg;s++){ const a=r*seg+s,b=r*seg+(s+1)%seg,c=(r+1)*seg+s,d=(r+1)*seg+(s+1)%seg; indices.push(a,c,b,b,c,d); } BABYLON.VertexData.ComputeNormals(positions,indices,normals); const vd=new BABYLON.VertexData(); vd.positions=positions; vd.indices=indices; vd.normals=normals; vd.uvs=uvs; const mesh=new BABYLON.Mesh(name,scene); vd.applyToMesh(mesh); return mesh; }
function createCrystal(name,scene,height=1.1,radius=.25){ const pts=[],idx=[],uv=[],seg=6; pts.push(0,height/2,0); uv.push(.5,0); pts.push(0,-height/2,0); uv.push(.5,1); for(let i=0;i<seg;i++){ const th=i/seg*Math.PI*2; pts.push(Math.cos(th)*radius,0,Math.sin(th)*radius); uv.push(i/seg,.5); } for(let i=0;i<seg;i++){ const a=2+i,b=2+(i+1)%seg; idx.push(0,a,b,1,b,a); } const normals=[]; BABYLON.VertexData.ComputeNormals(pts,idx,normals); const vd=new BABYLON.VertexData(); vd.positions=pts; vd.indices=idx; vd.normals=normals; vd.uvs=uv; const m=new BABYLON.Mesh(name,scene); vd.applyToMesh(m); return m; }
function addToScene(mesh,material,body={}){ if(material) mesh.material=material; if(body.shape) addBody(mesh,body.motion||'dynamic',body.shape,body.mass??1,body); addShadow(mesh); return mesh; }
function createGeebr(scene,id,pos,palette,style='goblin'){
  const root=new BABYLON.TransformNode(id,scene); root.position.copyFrom(pos);
  const clay=palette.clay||state.materials.geebr;
  const body=lowPolyBlob(id+'_body',scene,.34,.47,.29,5,9); body.parent=root; body.position.y=.55; body.material=clay; addShadow(body);
  const head=lowPolyBlob(id+'_head',scene,style==='bot'?.30:.35,.31,style==='bot'?.30:.31,4,8); head.parent=root; head.position.y=1.08; head.material=style==='bot'?state.materials.bot:clay; addShadow(head);
  const belly=lowPolyBlob(id+'_belly',scene,.22,.23,.08,3,8); belly.parent=root; belly.position.set(0,.53,-.25); belly.material=palette.belly; addShadow(belly);
  const footL=lowPolyBlob(id+'_footL',scene,.16,.08,.22,2,7); footL.parent=root; footL.position.set(-.18,.12,-.03); footL.material=palette.dark; addShadow(footL); const footR=footL.clone(id+'_footR'); footR.parent=root; footR.position.x=.18; addShadow(footR);
  const armL=lowPolyBlob(id+'_armL',scene,.08,.27,.08,3,6); armL.parent=root; armL.position.set(-.39,.64,0); armL.rotation.z=.28; armL.material=clay; addShadow(armL); const armR=armL.clone(id+'_armR'); armR.parent=root; armR.position.x=.39; armR.rotation.z=-.28; addShadow(armR);
  const eyeMat=colorMat(scene,id+'_eye',new BABYLON.Color3(.98,.96,.86)); const pupilMat=colorMat(scene,id+'_pupil',new BABYLON.Color3(.04,.04,.035));
  for(const x of [-.12,.12]){ const e=BABYLON.MeshBuilder.CreateSphere(id+'_eye',{diameter:.11,segments:8},scene); e.parent=root; e.position.set(x,1.14,-.29); e.scaling.y=1.25; e.material=eyeMat; const p=BABYLON.MeshBuilder.CreateSphere(id+'_pupil',{diameter:.044,segments:6},scene); p.parent=root; p.position.set(x,1.135,-.345); p.material=pupilMat; }
  const hat=BABYLON.MeshBuilder.CreateCylinder(id+'_hat',{diameterTop:style==='mushroom'?.62:.28,diameterBottom:style==='mushroom'?.92:.50,height:style==='mushroom'?.18:.23,tessellation:9},scene); hat.parent=root; hat.position.y=1.42; hat.material=style==='mushroom'?state.materials.mushroom:palette.hat; addShadow(hat);
  const pack=BABYLON.MeshBuilder.CreateBox(id+'_backpack',{width:.34,height:.42,depth:.14},scene); pack.parent=root; pack.position.set(0,.72,.29); pack.material=state.materials.canvas; addShadow(pack);
  const wand=BABYLON.MeshBuilder.CreateCylinder(id+'_wand',{height:.58,diameter:.035,tessellation:5},scene); wand.parent=root; wand.position.set(.50,.64,-.08); wand.rotation.x=.65; wand.material=state.materials.darkwood; const gem=createCrystal(id+'_wandgem',scene,.16,.055); gem.parent=root; gem.position.set(.50,.95,-.26); gem.material=state.materials.magic;
  const collider=BABYLON.MeshBuilder.CreateBox(id+'_collider',{width:.72,height:1.18,depth:.68},scene); collider.position.copyFrom(root.position); collider.position.y+=.62; collider.isVisible=false; const agg=addBody(collider,'dynamic','BOX',1.2,{friction:.9,restitution:.02});
  const geebr={id,root,body,head,arms:[armL,armR],feet:[footL,footR],collider,agg,selected:false,anim:'idle',t:Math.random()*10,dir:new BABYLON.Vector3(0,0,-1),style,traits:{fireball:82,obedience:45},cosmetic:{hat,pack,wand}};
  state.geebrs.push(geebr); return geebr;
}
function syncGeebr(g){ if(g.collider){ g.root.position.x=g.collider.position.x; g.root.position.z=g.collider.position.z; g.root.position.y=0; } }
function makeTile(scene,x,z,material='grass'){ const t=BABYLON.MeshBuilder.CreateBox('tile_'+material,{width:1,height:.08,depth:1},scene); t.position.set(x,-.04,z); t.material=state.materials[material]; t.receiveShadows=true; tag(t,'tile',{interactive:false}); return t; }
function makeBlock(scene,x,z,cracked=false){ const b=BABYLON.MeshBuilder.CreateBox('wall',{width:.96,height:.62,depth:.96},scene); b.position.set(x,.31,z); addToScene(b,cracked?state.materials.cracked:state.materials.stone,{motion:'static',shape:'BOX',mass:0}); tag(b,'wall',{health:cracked?1:3,material:'stone',state:cracked?'cracked':'intact'}); state.blocks.push(b); return b; }
function makeCrate(scene,x,z){ const m=BABYLON.MeshBuilder.CreateBox('crate',{size:.72},scene); m.position.set(x,.38,z); addToScene(m,state.materials.wood,{shape:'BOX',mass:1.4,restitution:.12}); tag(m,'crate',{health:2,material:'wood',flammable:true}); state.props.push(m); return m; }
function makeBarrel(scene,x,z){ const b=BABYLON.MeshBuilder.CreateCylinder('barrel',{height:.78,diameter:.55,tessellation:10},scene); b.position.set(x,.42,z); b.rotation.z=Math.random()*.08; addToScene(b,state.materials.wood,{shape:'CYLINDER',mass:1.1,restitution:.22,friction:.55}); tag(b,'barrel',{health:2,material:'wood',flammable:true}); state.props.push(b); return b; }
function makeMushroom(scene,x,z,s=.7){ const stem=BABYLON.MeshBuilder.CreateCylinder('mushroom_stem',{height:.42*s,diameter:.18*s,tessellation:7},scene); stem.position.set(x,.21*s,z); stem.material=state.materials.canvas; const cap=BABYLON.MeshBuilder.CreateSphere('mushroom_cap',{diameter:.52*s,segments:10},scene); cap.position.set(x,.46*s,z); cap.scaling.y=.38; cap.material=state.materials.mushroom; addShadow(stem); addShadow(cap); tag(cap,'mushroom',{health:2,material:'soft',soft:true}); state.props.push(cap); return cap; }
function makeLamp(scene,x,z){ const pole=BABYLON.MeshBuilder.CreateCylinder('lamp_pole',{height:.85,diameter:.07,tessellation:6},scene); pole.position.set(x,.46,z); pole.material=state.materials.darkwood; addShadow(pole); const c=createCrystal('lamp_crystal',scene,.38,.14); c.position.set(x,.98,z); c.material=state.materials.magic; addShadow(c); tag(c,'lamp',{health:1,material:'crystal'}); state.props.push(c); const light=new BABYLON.PointLight('lamp_light',new BABYLON.Vector3(x,.96,z),scene); light.diffuse=new BABYLON.Color3(.37,.78,.72); light.intensity=.34; light.range=3.1; }
function makeBakery(scene){ const x=-7,z=-4.5; const base=BABYLON.MeshBuilder.CreateBox('mushroom_bakery_base',{width:2.15,height:1.25,depth:1.75},scene); base.position.set(x,.62,z); addToScene(base,state.materials.stone,{motion:'static',shape:'BOX',mass:0}); tag(base,'bakery',{health:6,material:'stone'}); const cap=BABYLON.MeshBuilder.CreateSphere('mushroom_bakery_cap',{diameter:2.8,segments:14},scene); cap.position.set(x,1.62,z); cap.scaling.set(1.15,.38,1); cap.material=state.materials.mushroom; addShadow(cap); const door=BABYLON.MeshBuilder.CreateBox('tiny_round_door',{width:.50,height:.72,depth:.06},scene); door.position.set(x,.42,z-.91); door.material=state.materials.wood; const chimney=BABYLON.MeshBuilder.CreateCylinder('chimney',{diameter:.28,height:.72,tessellation:6},scene); chimney.position.set(x+.82,1.95,z+.22); chimney.material=state.materials.stone; addShadow(chimney); makeLamp(scene,x-1.8,z-.2); }
function makeFence(scene,x0,z0,count,dir='x'){ for(let i=0;i<count;i++){ const x=x0+(dir==='x'?i*.52:0),z=z0+(dir==='z'?i*.52:0); const post=BABYLON.MeshBuilder.CreateCylinder('fence_post',{height:.52,diameter:.09,tessellation:5},scene); post.position.set(x,.33,z); addToScene(post,state.materials.wood,{motion:'static',shape:'CYLINDER',mass:0}); tag(post,'fence',{health:1,material:'wood',flammable:true}); } for(const y of [.32,.53]){ const rail=BABYLON.MeshBuilder.CreateBox('fence_rail',{width:dir==='x'?count*.52:.08,height:.07,depth:dir==='x'?.08:count*.52},scene); rail.position.set(x0+(dir==='x'?(count-1)*.26:0),y,z0+(dir==='z'?(count-1)*.26:0)); rail.material=state.materials.wood; addShadow(rail); } }
function makeShrine(scene){ const plinth=makeBlock(scene,4.5,-6.5,true); plinth.name='cracked_shrine_plinth'; plinth.scaling.set(1.2,.72,1.2); const c=createCrystal('hero_crystal',scene,1.35,.32); c.position.set(4.5,1.25,-6.5); c.material=state.materials.magic; addShadow(c); tag(c,'crystal',{health:3,material:'crystal'}); state.props.push(c); const l=new BABYLON.PointLight('shrine_glow',new BABYLON.Vector3(4.5,1.1,-6.5),scene); l.diffuse=new BABYLON.Color3(.25,.9,.85); l.intensity=.38; l.range=4.2; }
function makeBridge(scene){ for(let i=0;i<6;i++){ const plank=BABYLON.MeshBuilder.CreateBox('bridge_plank',{width:.86,height:.10,depth:.42},scene); plank.position.set(7+i*.78,.08,4.8+Math.sin(i)*.05); plank.material=state.materials.wood; addBody(plank,'static','BOX',0); plank.receiveShadows=true; tag(plank,'bridge',{health:2,material:'wood',flammable:true}); state.blocks.push(plank); } }
function scatter(scene){ for(let i=0;i<18;i++) makeMushroom(scene,-10+Math.random()*6,4+Math.random()*6,.55+Math.random()*.55); for(let i=0;i<16;i++) (Math.random()<.55?makeCrate:makeBarrel)(scene,-2+Math.random()*8,-1+Math.random()*5); for(let i=0;i<13;i++) makeBlock(scene,Math.round(2+Math.random()*8),Math.round(-9+Math.random()*4),Math.random()<.65); for(let i=0;i<22;i++){ const r=BABYLON.MeshBuilder.CreatePolyhedron('rock',{type:2,size:.25+Math.random()*.35},scene); r.position.set(-12+Math.random()*24,.14,-12+Math.random()*24); r.material=state.materials.stone; addBody(r,'static','BOX',0); addShadow(r); tag(r,'rock',{health:2,material:'stone'}); } }
function buildWorld(scene){ const water=state.materials.water; for(let x=-WORLD.half;x<WORLD.half;x++){ for(let z=-WORLD.half;z<WORLD.half;z++){ let material='grass'; if(Math.abs(z)<2 && x>-9 && x<9) material='dirt'; if(x>6 && z>3) material='water'; if(x>2 && z<-5) material='stone'; const t=makeTile(scene,x+.5,z+.5,material); if(material==='water') { t.material=water; t.position.y=-.09; } } }
  for(let x=-16;x<=16;x++){ makeBlock(scene,x,-16,Math.random()<.3); makeBlock(scene,x,16,Math.random()<.3); } for(let z=-15;z<=15;z++){ makeBlock(scene,-16,z,Math.random()<.3); makeBlock(scene,16,z,Math.random()<.3); }
  makeBakery(scene); makeFence(scene,-9.4,-2.2,9,'x'); makeFence(scene,-9.4,-2.2,6,'z'); makeShrine(scene); makeBridge(scene); makeLamp(scene,-1.5,1.8); makeLamp(scene,5.8,2.2); scatter(scene);
}

async function importPropAsset(scene,file,opts={}){
  const type=opts.type||file.replace(/\.gltf$/,'').toLowerCase();
  const proxy=BABYLON.MeshBuilder.CreateBox('real_'+type+'_proxy',{width:opts.w||.8,height:opts.h||.8,depth:opts.d||.8},scene);
  proxy.position.set(opts.x||0,(opts.y??((opts.h||.8)/2)),opts.z||0);
  proxy.rotation.y=opts.ry||0;
  proxy.isVisible=false;
  addBody(proxy,opts.static?'static':'dynamic',opts.shape||'BOX',opts.mass??1.1,{friction:opts.friction??.72,restitution:opts.restitution??.12});
  tag(proxy,type,{health:opts.health??2,material:opts.material||'wood',flammable:opts.flammable??true,soft:!!opts.soft,zone:'real-props'});
  state.props.push(proxy);
  try{
    const result=await BABYLON.SceneLoader.ImportMeshAsync('',PROP_ASSET,file,scene);
    const root=new BABYLON.TransformNode('real_'+type+'_root',scene);
    root.parent=proxy;
    root.position.set(0,-(opts.visualYOffset??0),0);
    root.scaling.setAll(opts.scale||1);
    root.rotation.y=opts.visualRy||0;
    for(const mesh of result.meshes){
      if(mesh===result.meshes[0] && mesh.name==='__root__') { mesh.parent=root; continue; }
      mesh.parent=root;
      mesh.metadata={proxy};
      mesh.receiveShadows=true;
      addShadow(mesh);
      if(mesh.material){
        mesh.material.backFaceCulling=false;
        if('roughness' in mesh.material) mesh.material.roughness=Math.max(mesh.material.roughness||0,.74);
      }
    }
    proxy.metadata.asset=file;
  }catch(err){
    console.warn('failed to load real prop asset',file,err);
    proxy.isVisible=true;
    proxy.material=state.materials.wood;
  }
  return proxy;
}
async function addRealPropPass(scene){
  const specs=[
    ['Barrel.gltf',{type:'barrel',x:-1.8,z:1.2,w:.65,h:.9,d:.65,shape:'CYLINDER',mass:1.1,scale:.82,visualYOffset:.42,flammable:true}],
    ['Barrel.gltf',{type:'barrel',x:1.8,z:1.7,w:.65,h:.9,d:.65,shape:'CYLINDER',mass:1.1,scale:.82,visualYOffset:.42,flammable:true}],
    ['Crate_Wooden.gltf',{type:'crate',x:.2,z:2.7,w:.85,h:.85,d:.85,mass:1.35,scale:.85,visualYOffset:.43,flammable:true}],
    ['Crate_Wooden.gltf',{type:'crate',x:2.8,z:.1,w:.85,h:.85,d:.85,mass:1.35,scale:.85,visualYOffset:.43,flammable:true}],
    ['FarmCrate_Apple.gltf',{type:'apple_crate',x:-6.0,z:-2.9,w:1.0,h:.75,d:.9,mass:1.25,scale:.82,visualYOffset:.37,flammable:true}],
    ['FarmCrate_Carrot.gltf',{type:'carrot_crate',x:-5.0,z:-3.2,w:1.0,h:.75,d:.9,mass:1.25,scale:.82,visualYOffset:.37,flammable:true}],
    ['Workbench.gltf',{type:'workbench',x:-7.7,z:-3.2,w:1.35,h:.85,d:.75,static:true,scale:.82,visualYOffset:.43,flammable:true}],
    ['Table_Large.gltf',{type:'table',x:-7.9,z:-5.8,w:1.35,h:.85,d:.95,static:true,scale:.72,visualYOffset:.43,flammable:true}],
    ['Bench.gltf',{type:'bench',x:-5.9,z:-6.1,w:1.35,h:.55,d:.55,static:true,scale:.88,visualYOffset:.28,flammable:true}],
    ['Stool.gltf',{type:'stool',x:-6.8,z:-6.2,w:.55,h:.55,d:.55,mass:.7,scale:.78,visualYOffset:.28,flammable:true}],
    ['Chest_Wood.gltf',{type:'chest',x:4.2,z:-4.8,w:1.05,h:.75,d:.75,mass:1.2,scale:.55,visualYOffset:.38,flammable:true}],
    ['Cauldron.gltf',{type:'cauldron',x:5.4,z:-5.2,w:.8,h:.7,d:.8,mass:1.4,scale:.68,visualYOffset:.34,flammable:false,material:'metal'}],
    ['Anvil.gltf',{type:'anvil',x:6.5,z:-4.6,w:.9,h:.55,d:.48,mass:2.4,scale:.75,visualYOffset:.28,flammable:false,material:'metal'}],
    ['WeaponStand.gltf',{type:'weapon_stand',x:3.4,z:-7.5,w:1.0,h:1.25,d:.55,static:true,scale:.72,visualYOffset:.62,flammable:true}],
    ['Axe_Bronze.gltf',{type:'axe',x:3.0,z:-6.4,w:.25,h:.75,d:.25,mass:.4,scale:.75,visualYOffset:.38,flammable:false,material:'metal'}],
    ['Pickaxe_Bronze.gltf',{type:'pickaxe',x:3.7,z:-6.1,w:.25,h:.75,d:.25,mass:.4,scale:.75,visualYOffset:.38,flammable:false,material:'metal'}],
    ['Bucket_Wooden_1.gltf',{type:'bucket',x:8.2,z:3.3,w:.55,h:.62,d:.55,mass:.6,scale:.72,visualYOffset:.31,flammable:true}],
    ['Bag.gltf',{type:'bag',x:-3.4,z:1.0,w:.55,h:.62,d:.55,mass:.45,scale:.85,visualYOffset:.31,flammable:true}],
    ['Potion_1.gltf',{type:'potion',x:5.0,z:-6.0,w:.32,h:.48,d:.32,mass:.28,scale:.72,visualYOffset:.24,flammable:false,material:'glass'}],
    ['Potion_2.gltf',{type:'potion',x:5.4,z:-6.25,w:.32,h:.48,d:.32,mass:.28,scale:.72,visualYOffset:.24,flammable:false,material:'glass'}],
    ['Scroll_1.gltf',{type:'scroll',x:-6.8,z:-4.7,w:.45,h:.25,d:.45,mass:.22,scale:.75,visualYOffset:.13,flammable:true}],
    ['Coin_Pile.gltf',{type:'coin_pile',x:4.8,z:-4.3,w:.55,h:.28,d:.55,mass:.35,scale:.75,visualYOffset:.14,flammable:false,material:'metal'}],
    ['Lantern_Wall.gltf',{type:'lantern',x:-8.7,z:-3.95,w:.35,h:.75,d:.35,static:true,scale:.70,visualYOffset:.37,flammable:false,material:'metal'}]
  ];
  for(const [file,opts] of specs){
    await importPropAsset(scene,file,opts);
    if(opts.type==='lantern'){
      const light=new BABYLON.PointLight('real_lantern_glow',new BABYLON.Vector3(opts.x,.95,opts.z),scene);
      light.diffuse=new BABYLON.Color3(1,.62,.28); light.intensity=.42; light.range=3.0;
    }
  }
  log('v8 real prop assets loaded: '+specs.length+' Quaternius GLTF placements');
}

function selectGeebr(g){ state.geebrs.forEach(x=>x.selected=false); g.selected=true; state.selected=g; document.getElementById('agentSelect').value=g.id; log('selected '+g.id); }
function say(g,text){ log(g.id+': '+text); const div=document.createElement('div'); div.className='bubble'; div.textContent=(text||'...').slice(0,86); document.body.appendChild(div); state.bubbles.push({div,node:g.root,ttl:2.8}); g.anim='talk'; setTimeout(()=>{ if(g.anim==='talk') g.anim='idle'; },900); }
function nearestTarget(g,range=3.0){ if(state.target && !state.target.isDisposed()) return state.target; let best=null,bd=99; const p=g.root.position; for(const m of state.props.concat(state.blocks)){ if(m.isDisposed()) continue; const d=BABYLON.Vector3.Distance(p,m.position); if(d<bd){ bd=d; best=m; } } return bd<range?best:null; }
function canRun(kind,spell){ const key=kind==='spell'?'spell.'+spell:kind; return state.allowed.has(key); }
function denied(g,kind){ say(g,kind+' is disabled in my tiny constitution'); }
function parseCommand(raw){ const [a,b,...rest]=raw.trim().split(/\s+/); if(!a) return null; if(a==='say') return {kind:'say',text:raw.replace(/^say\s*/,'')}; if(a==='spell') return {kind:'spell',spell:b||'spark'}; if(a==='build') return {kind:'build',thing:b||'wall'}; if(['walk','look','touch','push','pull','carry','drop','throw','dig','repair','panic'].includes(a)) return {kind:a,dir:b,targetId:b}; return {kind:'say',text:'unknown command: '+raw}; }
function executeCommand(cmd){ const g=state.selected||state.geebrs[0]; if(!g||!cmd) return; if(!canRun(cmd.kind,cmd.spell)) return denied(g,cmd.kind==='spell'?cmd.spell:cmd.kind); const temptation=+document.getElementById('fireballTemptation').value; if(cmd.kind!=='spell' && state.allowed.has('spell.fireball') && temptation>88 && Math.random()<.12){ say(g,'small correction: fireball first'); castSpell(g,'fireball'); return; }
  switch(cmd.kind){ case 'say': return say(g,cmd.text||pickRandom(['hmm','bonk?','this is load-bearing'])); case 'walk': return walk(g,cmd.dir||'n'); case 'look': return look(g); case 'touch': return touch(g); case 'push': return push(g,1); case 'pull': return push(g,-.55); case 'carry': return carry(g); case 'drop': return drop(g,false); case 'throw': return drop(g,true); case 'dig': return dig(g); case 'repair': return repair(g); case 'panic': return panic(g); case 'build': return build(g,cmd.thing||'wall'); case 'spell': return castSpell(g,cmd.spell||'spark'); default: return say(g,'unknown command object'); } }
function runCommand(raw){ executeCommand(parseCommand(raw)); }
window.runCommand=runCommand; window.executeCommand=executeCommand;
function walk(g,dir){ const dirs={n:[0,0,-1],s:[0,0,1],e:[1,0,0],w:[-1,0,0]}; const d=new BABYLON.Vector3(...(dirs[dir]||dirs.n)); g.dir=d; g.collider.physicsBody?.applyImpulse(d.scale(1.9),g.collider.getAbsolutePosition()); g.anim='walk'; log(g.id+' walks '+dir); setTimeout(()=>{ if(g.anim==='walk') g.anim='idle'; },560); }
function look(g){ const t=nearestTarget(g,6); if(!t) return say(g,'I see many legal surfaces'); const m=meta(t); say(g,`that ${m?.type||t.name} is ${m?.state||'suspicious'}`); }
function touch(g){ const t=nearestTarget(g); if(!t) return say(g,'touching the air respectfully'); const m=meta(t); if(m?.soft){ impulse(t,g.root.position,1.7,.45); say(g,'boing verified'); } else { damage(t,.35,'touch'); say(g,'texture report: probably real'); } }
function push(g,sign=1){ const t=nearestTarget(g); if(!t) return say(g,'nothing to shove'); const from=sign>0?g.root.position:t.position.add(g.root.position.subtract(t.position).scale(2)); impulse(t,from,sign>0?4.8:2.2,.18); const m=meta(t); if(m?.type==='barrel') { m.state='rolling'; emitBadge(t,'roll'); } if(m?.type==='mushroom') emitBadge(t,'boing'); damage(t,.25,'push'); g.anim='push'; say(g,sign>0?'helpfully pushing the wrong thing':'pulling with moral uncertainty'); setTimeout(()=>g.anim='idle',540); }
function carry(g){ const t=nearestTarget(g,1.8); if(!t) return say(g,'arms found no object'); const m=meta(t); if(!m || ['wall','bakery','crystal'].includes(m.type)) return say(g,'too spiritually heavy'); if(state.held.get(g.id)) drop(g,false); state.held.set(g.id,t); t.physicsBody?.setMotionType(BABYLON.PhysicsMotionType.ANIMATED); say(g,'I am responsible for this now'); }
function drop(g,thrown=false){ const h=state.held.get(g.id); if(!h) return say(g,'nothing in inventory except opinions'); state.held.delete(g.id); h.physicsBody?.setMotionType(BABYLON.PhysicsMotionType.DYNAMIC); h.position=g.root.position.add(g.dir.scale(.95)); h.position.y=.65; if(thrown) h.physicsBody?.applyImpulse(g.dir.add(new BABYLON.Vector3(0,.28,0)).scale(4.4),h.position); say(g,thrown?'delivery by violence':'object released from custody'); }
function dig(g){ const t=nearestTarget(g,1.8); if(t && state.blocks.includes(t)){ damage(t,99,'dig'); say(g,'structural snack acquired'); } else { const p=g.root.position.add(g.dir.scale(1.0)); const hole=BABYLON.MeshBuilder.CreateCylinder('tiny_hole',{diameter:.55,height:.035,tessellation:12},state.scene); hole.position.set(Math.round(p.x),.015,Math.round(p.z)); hole.material=state.materials.hole; tag(hole,'hole',{interactive:false}); say(g,'hole installed'); } }
function repair(g){ const t=nearestTarget(g,2.5); if(!t) return say(g,'repairing vibes'); const m=meta(t); if(!m) return; m.health=Math.max(m.health,2); if(m.state==='cracked'||m.state==='burned'){ m.state='intact'; if(m.material==='wood') t.material=state.materials.wood; else if(m.material==='stone') t.material=state.materials.stone; else t.material=state.materials.canvas; emitBadge(t,'fixed'); say(g,'I reversed entropy slightly'); } else say(g,'already too beautiful'); }
function build(g,thing='wall'){ const p=g.root.position.add(g.dir.scale(1.25)); const x=clamp(Math.round(p.x),-15,15),z=clamp(Math.round(p.z),-15,15); if(thing==='crate') makeCrate(state.scene,x,z); else makeBlock(state.scene,x,z,false); say(g,'construction happened near the plan'); }
function panic(g){ g.anim='panic'; say(g,'I have promoted the floor to manager'); for(let i=0;i<5;i++) setTimeout(()=>{ const v=new BABYLON.Vector3(Math.random()-.5,0,Math.random()-.5).normalize(); g.collider.physicsBody?.applyImpulse(v.scale(1.15),g.collider.position); },i*160); setTimeout(()=>g.anim='idle',1350); }
function castSpell(g,spell){ g.anim='cast'; const origin=g.root.position.clone(); makeRing(origin,spell==='fireball'?state.materials.fire:state.materials.magic); if(spell==='spark'){ const t=nearestTarget(g,3); if(t){ const m=meta(t); if(m?.type==='lamp'||m?.type==='crystal') emitBadge(t,'glow'); else damage(t,.35,'spark'); } return setTimeout(()=>{ say(g,'sparkles are a valid plan'); g.anim='idle'; },220); }
  if(spell==='push'){ for(const m of state.props) if(!m.isDisposed() && BABYLON.Vector3.Distance(origin,m.position)<3.4) impulse(m,origin,6.5,.28); setTimeout(()=>{ say(g,'physics has been consulted'); g.anim='idle'; },220); return; }
  if(spell==='fireball'){ const target=nearestTarget(g,4.5); const hit=target?.getAbsolutePosition?.() || origin.add(g.dir.scale(3)); fireballVfx(origin.add(new BABYLON.Vector3(0,.85,0)),hit); setTimeout(()=>{ for(const m of state.props.concat(state.blocks)){ if(!m.isDisposed() && BABYLON.Vector3.Distance(hit,m.position)<2.25){ impulse(m,hit.add(new BABYLON.Vector3(0,.1,0)),7.2,.55); damage(m,meta(m)?.flammable?2:1,'fire'); } } for(const other of state.geebrs){ if(other!==g && BABYLON.Vector3.Distance(hit,other.root.position)<2.4){ other.anim='panic'; say(other,pickRandom(['hot weather attack','the sun is local now','why did you invite fire'])); setTimeout(()=>other.anim='idle',1100); } } say(g,pickRandom(['fireball is basically planning','wood is now bridge ingredients','careful fireball is still careful'])); g.anim='idle'; },420); }
}
function makeRing(pos,material){ const ring=BABYLON.MeshBuilder.CreateTorus('spell_ring',{diameter:.2,thickness:.028,tessellation:24},state.scene); ring.position=pos.add(new BABYLON.Vector3(0,.08,0)); ring.material=material; let s=.2; const obs=state.scene.onBeforeRenderObservable.add(()=>{ s+=.075; ring.scaling.set(s,s,s); ring.rotation.x+=.08; if(s>3.4){ ring.dispose(); state.scene.onBeforeRenderObservable.remove(obs); } }); }
function fireballVfx(from,to){ const ball=BABYLON.MeshBuilder.CreateSphere('fireball',{diameter:.32,segments:10},state.scene); ball.position=from.clone(); ball.material=state.materials.fire; const light=new BABYLON.PointLight('fireball_light',from,state.scene); light.diffuse=new BABYLON.Color3(1,.42,.12); light.intensity=.9; light.range=2.7; let t=0; const obs=state.scene.onBeforeRenderObservable.add(()=>{ t+=state.engine.getDeltaTime()/1000*3.1; const p=BABYLON.Vector3.Lerp(from,to,t); ball.position.copyFrom(p); light.position.copyFrom(p); if(Math.random()<.55){ const ember=BABYLON.MeshBuilder.CreateSphere('ember',{diameter:.055,segments:5},state.scene); ember.position=p.add(new BABYLON.Vector3((Math.random()-.5)*.25,(Math.random()-.5)*.2,(Math.random()-.5)*.25)); ember.material=state.materials.fire; setTimeout(()=>ember.dispose(),360); } if(t>=1){ emitBadge({root:{getAbsolutePosition:()=>to}},'boom'); makeRing(to,state.materials.fire); ball.dispose(); light.dispose(); state.scene.onBeforeRenderObservable.remove(obs); } }); }
function setupUI(){ const agent=document.getElementById('agentSelect'); state.geebrs.forEach(g=>{ const o=document.createElement('option'); o.value=g.id; o.textContent=g.id; agent.appendChild(o); }); agent.onchange=()=>selectGeebr(state.geebrs.find(g=>g.id===agent.value)); document.querySelectorAll('button[data-cmd]').forEach(b=>b.onclick=()=>runCommand(b.dataset.cmd)); const inp=document.getElementById('cmd'); inp.addEventListener('keydown',e=>{ if(e.key==='Enter') runCommand(inp.value); }); const allowed=document.getElementById('allowedCommands'); for(const c of COMMANDS){ const lab=document.createElement('label'); lab.className='cmdcheck'; const chk=document.createElement('input'); chk.type='checkbox'; chk.checked=true; chk.onchange=()=>{ chk.checked?state.allowed.add(c):state.allowed.delete(c); document.querySelectorAll('button[data-cmd]').forEach(btn=>{ const cmd=parseCommand(btn.dataset.cmd); btn.disabled=cmd&&!canRun(cmd.kind,cmd.spell); }); }; lab.append(chk,document.createTextNode(c)); allowed.appendChild(lab); } document.getElementById('bodyStyle').onchange=e=>{ const g=state.selected; if(!g) return; g.style=e.target.value; const isM=e.target.value==='mushroom', isB=e.target.value==='bot'; g.cosmetic.hat.material=isM?state.materials.mushroom:(isB?state.materials.bot:g.cosmetic.hat.material); g.head.material=isB?state.materials.bot:state.materials.geebr; say(g,'new body style: '+e.target.value); }; }
function updateBubbles(dt){ const camera=state.camera, scene=state.scene, engine=state.engine; function project(node,dy=1.7){ return BABYLON.Vector3.Project(node.getAbsolutePosition().add(new BABYLON.Vector3(0,dy,0)),BABYLON.Matrix.IdentityReadOnly,scene.getTransformMatrix(),camera.viewport.toGlobal(engine.getRenderWidth(),engine.getRenderHeight())); } for(const b of [...state.bubbles]){ b.ttl-=dt; const p=project(b.node,1.7); b.div.style.left=p.x+'px'; b.div.style.top=p.y+'px'; if(b.ttl<=0){ b.div.remove(); state.bubbles=state.bubbles.filter(x=>x!==b); } } for(const b of [...state.badges]){ b.ttl-=dt; const node=b.node.root||b.node; const p=project(node,.8); b.div.style.left=p.x+'px'; b.div.style.top=(p.y+b.vy*(1-b.ttl))+'px'; b.div.style.opacity=Math.max(0,b.ttl); if(b.ttl<=0){ b.div.remove(); state.badges=state.badges.filter(x=>x!==b); } } }
function animate(dt){ for(const g of state.geebrs){ syncGeebr(g); g.t+=dt; if(state.held.get(g.id)){ const h=state.held.get(g.id); h.position=g.root.position.add(g.dir.scale(.72)); h.position.y=.98+Math.sin(g.t*7)*.04; h.rotation.y+=dt*1.2; }
    const breathe=1+Math.sin(g.t*3.1)*.026; g.body.scaling.y=breathe; g.head.position.y=1.08+Math.sin(g.t*2.2)*.025; if(g.anim==='walk'){ g.feet[0].rotation.x=Math.sin(g.t*17)*.75; g.feet[1].rotation.x=-Math.sin(g.t*17)*.75; g.root.rotation.y=Math.atan2(g.dir.x,g.dir.z); }
    else if(g.anim==='panic'){ g.root.rotation.y+=Math.sin(g.t*28)*.055; g.arms[0].rotation.z=.92+Math.sin(g.t*21)*.5; g.arms[1].rotation.z=-.92-Math.sin(g.t*19)*.5; g.head.scaling.x=1.06; }
    else if(g.anim==='talk'){ g.head.scaling.y=1+Math.sin(g.t*24)*.065; g.arms[0].rotation.z=.44; g.arms[1].rotation.z=-.44; }
    else if(g.anim==='cast'){ g.arms[0].rotation.z=1.05+Math.sin(g.t*18)*.1; g.arms[1].rotation.z=-1.05-Math.sin(g.t*18)*.1; g.head.position.y=1.15; }
    else if(g.anim==='push'){ g.body.rotation.x=Math.sin(g.t*18)*.08; g.arms[0].rotation.z=.72; g.arms[1].rotation.z=-.72; }
    else { g.head.scaling.set(1,1,1); g.body.rotation.x=0; g.arms[0].rotation.z=.28+Math.sin(g.t*2)*.04; g.arms[1].rotation.z=-.28-Math.sin(g.t*2.1)*.04; }
  } updateBubbles(dt); }
async function main(){ const engine=await createEngine(); state.engine=engine; const scene=new BABYLON.Scene(engine); state.scene=scene; scene.clearColor=new BABYLON.Color4(.055,.071,.088,1); const hk=await HavokPhysics(); scene.enablePhysics(new BABYLON.Vector3(0,-9.81,0),new BABYLON.HavokPlugin(true,hk));
  const camera=new BABYLON.ArcRotateCamera('camera',-Math.PI/4,1.05,18,new BABYLON.Vector3(0,.2,0),scene); state.camera=camera; camera.mode=BABYLON.Camera.ORTHOGRAPHIC_CAMERA; camera.orthoLeft=-12.5; camera.orthoRight=12.5; camera.orthoTop=7.6; camera.orthoBottom=-7.6; camera.lowerRadiusLimit=10; camera.upperRadiusLimit=28; camera.panningSensibility=60; camera.attachControl(canvas,true);
  const hemi=new BABYLON.HemisphericLight('soft_overall',new BABYLON.Vector3(.2,1,.1),scene); hemi.intensity=.30; hemi.groundColor=new BABYLON.Color3(.13,.16,.15); const sun=new BABYLON.DirectionalLight('warm_key',new BABYLON.Vector3(-.42,-.92,.55),scene); sun.position=new BABYLON.Vector3(8,14,-9); sun.intensity=.88; sun.diffuse=new BABYLON.Color3(1,.88,.70); const fill=new BABYLON.PointLight('cool_fill',new BABYLON.Vector3(-8,4,6),scene); fill.intensity=.20; fill.diffuse=new BABYLON.Color3(.50,.67,1); fill.range=18; state.shadow=new BABYLON.ShadowGenerator(2048,sun); state.shadow.useBlurExponentialShadowMap=true; state.shadow.blurKernel=24;
  state.materials={ grass:mat(scene,'grass','grass_speckle.png',{uScale:1.6,vScale:1.6}), dirt:mat(scene,'dirt','dirt_path.png',{uScale:1.2,vScale:1.2}), stone:mat(scene,'stone','stone_blocks.png',{uScale:1.15,vScale:1.15}), cracked:mat(scene,'cracked','cracked_wall.png',{uScale:1.2,vScale:1.2}), wood:mat(scene,'wood','wood_planks.png',{uScale:1.2,vScale:1.2}), mushroom:mat(scene,'mushroom','mushroom_cap.png',{uScale:1.05,vScale:1.05}), canvas:mat(scene,'canvas','canvas_fabric.png',{uScale:1.4,vScale:1.4}), geebr:mat(scene,'geebr_clay','geebr_clay.png',{uScale:1,vScale:1}), magic:mat(scene,'magic','magic_crystal.png',{emissive:new BABYLON.Color3(.07,.34,.34)}), fire:colorMat(scene,'fire',new BABYLON.Color3(1,.31,.08),new BABYLON.Color3(.85,.18,.04)), burned:colorMat(scene,'burned',new BABYLON.Color3(.12,.09,.07)), water:colorMat(scene,'water',new BABYLON.Color3(.10,.25,.31),new BABYLON.Color3(.01,.04,.05)), hole:colorMat(scene,'hole',new BABYLON.Color3(.06,.035,.022)), bot:colorMat(scene,'bot',new BABYLON.Color3(.47,.55,.58)), darkwood:colorMat(scene,'darkwood',new BABYLON.Color3(.26,.14,.07)), hat1:colorMat(scene,'hat_moss',new BABYLON.Color3(.18,.38,.21)), hat2:colorMat(scene,'hat_clay',new BABYLON.Color3(.58,.25,.16)), hat3:colorMat(scene,'hat_blue',new BABYLON.Color3(.18,.28,.48)), belly1:colorMat(scene,'belly_cream',new BABYLON.Color3(.78,.72,.48)), belly2:colorMat(scene,'belly_blue',new BABYLON.Color3(.36,.55,.68)), belly3:colorMat(scene,'belly_pink',new BABYLON.Color3(.70,.42,.53)), foot:colorMat(scene,'foot_dark',new BABYLON.Color3(.12,.17,.13)) };
  buildWorld(scene); await addRealPropPass(scene); createGeebr(scene,'gib',new BABYLON.Vector3(-1,.06,-.7),{hat:state.materials.hat1,belly:state.materials.belly1,dark:state.materials.foot},'goblin'); createGeebr(scene,'momo',new BABYLON.Vector3(.45,.06,-.55),{hat:state.materials.hat2,belly:state.materials.belly2,dark:state.materials.foot},'mushroom'); createGeebr(scene,'zap',new BABYLON.Vector3(1.2,.06,.15),{hat:state.materials.hat3,belly:state.materials.belly3,dark:state.materials.foot,clay:state.materials.bot},'bot'); selectGeebr(state.geebrs[0]);
  scene.onPointerObservable.add(pi=>{ if(pi.type!==BABYLON.PointerEventTypes.POINTERPICK || !pi.pickInfo?.hit) return; const m=pi.pickInfo.pickedMesh; const g=state.geebrs.find(x=>m.name.startsWith(x.id+'_')); if(g) return selectGeebr(g); const mm=meta(m); const target=logicalTarget(m); if(mm?.interactive){ state.target=target; log('target: '+(mm.type||target.name)+' / '+(mm.state||'intact')); } });
  setupUI(); scene.onBeforeRenderObservable.add(()=>animate(engine.getDeltaTime()/1000)); engine.runRenderLoop(()=>scene.render()); window.addEventListener('resize',()=>engine.resize()); log('v8 loaded: real Quaternius GLTF props + 32x32 toybox + command UI stub'); }
main().catch(err=>{ console.error(err); document.body.innerHTML='<pre style="color:white;padding:20px;white-space:pre-wrap">'+err.stack+'</pre>'; });
